    version: "3.9"

    services:
      postgres:
        image: postgres:16-alpine
        container_name: videoflow-postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data
          - ./scripts/create-dbs.sh:/docker-entrypoint-initdb.d/create-dbs.sh
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 5s
          timeout: 5s
          retries: 5

      redis:
        image: redis:7-alpine
        container_name: videoflow-redis
        ports:
          - "6379:6379"
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
          interval: 5s
          timeout: 3s
          retries: 5

      kafka:
        image: confluentinc/cp-kafka:7.9.0
        container_name: videoflow-kafka
        depends_on: []     # больше не зависит от kafka-controller
        environment:
          CLUSTER_ID: "MkU3OEVBNTcwNTJENDExQk"
          KAFKA_NODE_ID: 1
          KAFKA_PROCESS_ROLES: controller,broker
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://127.0.0.1:9093
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
          KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        ports:
          - "9092:9092"
        volumes:
          - kafka_data:/var/lib/kafka/data
        healthcheck:
          test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
          interval: 10s
          timeout: 5s
          retries: 5
    
      minio:
        image: minio/minio:latest
        container_name: videoflow-minio
        command: server /data --console-address ":9001"
        environment:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
        ports:
          - "9000:9000"
          - "9001:9001"
        volumes:
          - minio_data:/data
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
          interval: 10s
          timeout: 5s
          retries: 5

    volumes:
      postgres_data:
      kafka_data:
      minio_data: